list: $/acte/clubmanager/models/category/columns.yaml
modelClass: Acte\ClubManager\Models\Category
title: Category
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'acte/clubmanager/categories/update/:id'
