list: $/acte/clubmanager/models/performance/columns.yaml
modelClass: Acte\ClubManager\Models\Performance
title: Performances
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'acte/clubmanager/performances/update/:id'
