list: $/acte/clubmanager/models/member/columns.yaml
modelClass: Acte\ClubManager\Models\Member
title: Member
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'acte/clubmanager/members/update/:id'
filter: config_filter.yaml
