list: $/acte/clubmanager/models/ticket/columns.yaml
modelClass: Acte\ClubManager\Models\Ticket
title: Ticket
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'acte/clubmanager/tickets/update/:id'
filter: config_filter.yaml
defaultSort: 'expire_date'
