list: $/acte/clubmanager/models/goal/columns.yaml
modelClass: Acte\ClubManager\Models\Goal
title: Goals
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'acte/clubmanager/goals/update/:id'
