list: $/acte/clubmanager/models/session/columns.yaml
modelClass: Acte\ClubManager\Models\Session
title: Session
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'acte/clubmanager/sessions/update/:id'
filter: config_filter.yaml
defaultSort: 'date'
